Add the ability to override the cc address
cloudfoundry/loggregator-release pull request #415
Opened 2021-05-07 19:23 UTC by andrew-edgar

Changed to fix the override ability of the cc address.

2021-05-07 19:38 UTC, Benjamintf1 commented
This might take a bit to investigate. PR pipeline seems to have trouble with branches with the same name 😨. It's *somewhat* new for me to use this way, so I'm going to try and get it to work. Might take a bit tho.

2021-05-07 19:54 UTC, Benjamintf1 commented
They're actually running now.

2021-05-07 20:23 UTC, Benjamintf1 commented
@andrew-edgar I'm taking a little bit of a look, but this is the error I'm seeing right now
![image](https://user-images.githubusercontent.com/2761008/117504518-d10ca780-af3f-11eb-94f5-e7ebbf79ea5c.png)

2021-05-07 20:27 UTC, Benjamintf1 requested changes

2021-05-07 20:27 UTC, Benjamintf1 commented on jobs/reverse_log_proxy/templates/bpm.yml.erb
> +  if_p("loggregator.doppler.addrs") { |daddrs|
The order changed on the list, but loggregator.doppler.addrs has a default of '[]' unlike TC which has no default. Please change the default this property to not exist.

2021-05-11 16:33 UTC, andrew-edgar commented
That default for doppler.addrs was not my code but I removed the default as requested

2021-05-11 17:10 UTC, Benjamintf1 commented
![image](https://user-images.githubusercontent.com/2761008/117856852-5bf3e780-b249-11eb-8e60-69d6642b0934.png)

This is the failure.

2021-05-11 17:27 UTC, Benjamintf1 commented
you're going to want to make that change on *all* the jobs, namely rlp(the currently failing job).

2021-05-11 17:53 UTC, Benjamintf1 approved these changes

2021-05-11 17:53 UTC, merged

2021-05-11 19:12 UTC, Benjamintf1 commented
@andrew-edgar https://github.com/cloudfoundry/loggregator-release/releases/tag/v106.6.0